---
dist: bionic
sudo: required

language: python
python:
  - "3.7"

services:
  - docker

git:
  submodules:
    false

before_install:
  - git clone https://github.com/lean-delivery/ansible-lint-rules.git ~/ansible-lint-rules

install:
  - pip3 install --upgrade ansible==2.9.* docker yamllint
  - pip3 install git+https://github.com/ansible/ansible-lint.git@v4.3.0a0
  - ansible --version
  - ansible-lint --version

script:
  - yamllint . -c .yamllint
  - ansible-lint . -c .ansible-lint

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
